# Generated by Django 5.0.6 on 2024-05-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_city_country_alter_blogentry_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
