# Generated by Django 5.0.6 on 2024-05-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_blogentry_imagelink_trip_imagelink_tripphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='currentTrip',
        ),
    ]
